name: Implementar en AWS CodeDeploy

on:
  workflow_run:
    workflows: ["Java CI con Gradle"]
    types: 
      - completed

jobs:
  
  deploy:
    runs-on: ubuntu-20.04
    if: ${{github.event.workflow_run.conclusion}} == 'success'
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Configurar CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "CodeDeploy" \
            --deployment-group-name "CodeDeploy_Group" \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}